export const ROUTES = {
  LOGIN: '/login',
  INVITATION: '/invitation/:token',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  HOME: '/',
  PROJECTS: '/projects',
  PROJECT_DETAIL: '/projects/:id',
  PROJECT_MEMBERS: '/projects/:id/members',
  CAMPAIGNS: '/campaigns',
  CAMPAIGN_NEW: '/projects/:projectId/campaigns/new',
  CAMPAIGN_DETAIL: '/projects/:projectId/campaigns/:campaignId',
  CAMPAIGN_EDIT: '/projects/:projectId/campaigns/:campaignId/edit',
  CAMPAIGN_POSTS: '/projects/:projectId/campaigns/:campaignId/posts',
  CAMPAIGN_COMMENTS: '/projects/:projectId/campaigns/:campaignId/comments',
  POSTS: '/posts',
  POST_DETAIL: '/projects/:projectId/campaigns/:campaignId/posts/:postId',
  PROFILES: '/profiles',
  PROFILES_NEW: '/profiles/new',
  PROFILE_DETAIL: '/profiles/:id',
  PROFILES_CATEGORIES: '/profiles/categories',
  PROFILES_TIERS: '/profiles/tiers',
  MY_ACCOUNT: '/my-account',
  COST: '/cost',
  USERS: '/users',
  SETTINGS: '/settings',
} as const
